# Generated by Django 2.2.11 on 2020-03-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE extension "uuid-ossp";
            ALTER TABLE authors_authors
            ALTER COLUMN id
            SET DEFAULT uuid_generate_v4();
            """
        )
    ]
